config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "works#index"
  resources :users, only: [:show, :edit, :update]
  resources :works do
  collection do
    get :indextop
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  with_options presence: true do
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, on: :create
  validates :full_name
  validates :birthday
  validates :genre
  validates :profile
  end

  has_many :works
  has_one_attached :image
end

app/models/work.rb
class Work < ApplicationRecord

  validates :image, presence: true
  belongs_to :user
  has_one_attached :image



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:full_name, :artist_name, :down_name, :birthday, :genre, :profile, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :artist_name, :down_name, :birthday, :genre, :profile, :image])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  private
  def user_params
    params.require(:user).permit(:image)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :top_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    user = User.find(params[:id])
    @works = user.works
  end

  private
  def user_params
    params.require(:user).permit(:image, :full_name, :artist_name, :birthday, :genre, :profile)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :artist_name, :birthday, :genre, :profile])

    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :artist_name, :birthday, :genre, :profile])
  end

  def top_user
    unless current_user.id
      redirect_to root_path
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :find_work, only: [:show, :edit, :update, :destroy]
  before_action :top_work, only: [:edit, :update, :destroy]


def index
end

def show
end

def new
  @work = Work.new
end

def create
  @work = Work.new(work_params)
  if @work.save
    redirect_to user_path(current_user.id)
  else
    render :new
  end
end

def edit

end

def update
  if @work.update(work_params)
    redirect_to work_path
  else
    render :edit
  end
end

def destroy
  if @work.destroy
    redirect_to user_path(current_user.id)
  end
end

  private

  def work_params
    params.require(:work).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def find_work
    @work = Work.find(params[:id])
  end

  def top_work
    if current_user.id != @work.user_id 
    redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portplus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@1,300;1,400&family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/users/show.html.erb
<div id="hamburger">
  <span class="inner_line" id="line1"></span>
  <span class="inner_line" id="line2"></span>
  <span class="inner_line" id="line3"></span>
</div>


<nav id="nav">
  <ul>
    <li><a href="#profile">PROFILE</a></li>
    <% if user_signed_in? %>
    <% if current_user.id == @user.id %>
    <li><%= link_to "EDIT PROFILE", edit_user_registration_path, class:"toplink"%></li>
    <% end %>
    <% end %>
    <li><a href="#works">WORKS</a></li>
    <% if user_signed_in? %>
    <% if current_user.id == @user.id %>
    <li><%= link_to "NEW WORK", new_work_path, class:"toplink"%></li>
    <% end %>
    <% end %>
    <li><%= link_to "TOP PAGE", indextop_works_path, class:"toplink"%></li>
  </ul>
</nav>

<div class="header-user">
<% if @user.image.attached?%>
<%= image_tag @user.image, class: 'header-image' %>
<% else %>
<%= image_tag "portplus.flower.png", class:"header-image" %>
<% end %>
</div> 
<div class="artist-name">
    -<%= @user.artist_name %>&emsp;WORKS-
</div>

<div class="card-wrapper">
<a name="work"></a>
<div class="card-line"></div>
<ul class="lists">

  <%# /投稿されてない場合 %>
  <% if @works[0] == nil %>
  <li class="image_list">
  <div class="card">
  <%=  image_tag("IMG_4357.JPG", class: :card_img ) %>
  <div class="card_title">
    <P>タイトル</P>
  </div>
</div>
</li>
  <li class="image_list">
  <div class="card">
  <%=  image_tag("IMG_4807.PNG", class: :card_img ) %>
  <div class="card_title">
    <P>タイトル</P>
  </div>
</div>
</li>
  <li class="image_list">
  <div class="card">
  <%=  image_tag("IMG_4808.PNG", class: :card_img ) %>
  <div class="card_title">
    <P>タイトル</P>
  </div>
</div>
</li>
    <div class='new-works'>
      <p>このように投稿されます。</p>
      <p>画面左上のメニューから作品を投稿してみましょう！</p>
    </div>
  <% end %>

<% @works.each do |work| %>
<li class="image_list">
<div class="card">
  <%= link_to image_tag(work.image, class: :card_img ), work_path(work.id) %>
  <div class="card_title">
    <%= work.title %>
  </div>
</div>
</li>
<% end %>
</ul>
<div class="card-line1"></div>
</div>

<a name="profile"></a>
<div class="profile">
<div class="profile-title">-PROFILE-</div> 
<div class="profile-contents">
  <div class="profile-temple">
    <p>artist name:</p>
    <%= @user.artist_name %>
  </div>
  <div class="profile-temple">
    <p>full name:</p>
    <%= @user.full_name %>
  </div>
  <div class="profile-temple">
    <p>DOB:</p>
    <%= @user.birthday %>
  </div>
    <div class="profile-temple">
    <p>genre:</p>
    <%= @user.genre %>
  </div>
  <div class="profile-sub">
  profile:
    <div class="profile-pr"><%= @user.profile %></div>
  </div>
</div>
  <div class="card-line1"></div>
</div>

<p class="site-header">2021 portplus+ All Rights Reserved.</p>

app/views/works/edit.html.erb
<div class="sign-up-logo1">
<%= image_tag "portplus.flower.png", class:"flower" %>
<%= link_to image_tag("portplus-logo2.png", class:"sign-up-logo2"), user_path(current_user.id) %>
</div>
<div class="sign-up-message">
<p class="new-work-font">EDIT WORK !!</p>
</div>

<%= form_with model: @work, class: 'registration-main', local: true do |f| %>
<div class="sign-up-page">

<div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">タイトル</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :title, class:"input-genre", id:"title", placeholder:"任意" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">キャッチコピー(任意)</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :catch_copy, class:"input-genre", id:"catch_copy", placeholder:"任意" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">コンセプト(任意)</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :concept, class:"input-genre", id:"concept", placeholder:"任意" %>
    </div>
  </div>

      <div class="form-group">
      <div class="click-upload">
        <P>作品を選択 ※必須</p>
        <%= f.file_field :image, id:"header-image" %>
      </div>
    </div>

  <div class="sign-up-btn">
      <%= f.submit "編集を確定", class:"sign-up-color-btn" %>
  </div>
</div>
<% end %>

app/views/works/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

  <div class="slide">
    <div class="slide1">
      <div class="background1">
        <%= image_tag "portplus-logo.png", class:"portplus-logo" %>
      </div>
    </div>
  </div>

    <div class="slide2">
      <div class="home-img">
        <%= image_tag "border2.png" %>
      </div>
      <div class="home-img2">
        <%= image_tag "flower.png" %>
      </div>
          <header>
            <div class="header-left">
              <%= image_tag("portplus-logo3.png", class:"portplus-logo2") %>
              <ul>
                <li><%= link_to 'sample', user_path(44), class: "sample" %></li>
                <li>service</li>
              </ul>
            </div>
            <div class="header-right">
              <ul>
                  <% if user_signed_in? %>
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "login-color" %></li>
                  <li><%= link_to 'マイページへ', user_path(current_user.id), class: "new" %></li>
                  <% else %>
                  <li><%= link_to 'ログイン', new_user_session_path, class: "login-color" %></li>
                  <li><%= link_to '新規登録', new_user_registration_path, class: "new" %></li>
                  <% end %>
              </ul>
            </div>
          </header>
          <body>
          <div class="scroll">
          <a>scroll </a>
          </div>
          <div class="home-box">
            <div class="home">
              <p>オリジナルのポートフォリオを作成しよう。</p>
              <h1>あなたの<span>作品</span>に<br>
              色付けを。</h1>
            </div>
            <div class="make-up">
              <% if user_signed_in? %>
                <li><%= link_to 'make up portfolio >', user_path(current_user.id), class: "make" %></li>
              <% else %>
                <li><%= link_to 'make up portfolio >', new_user_registration_path, class: "make" %></li>
              <% end %>
            </div>
          </div>
          </body>

  <div class="service-box">
    <div class="home-box2"></div>
    <div class="service-box3">
      <div class="service-img">
        <%= image_tag("design2.png", class:"design2") %>
        <%= image_tag("design1.png", class:"design1") %>
      </div>
      <div class="service">
        <p>SERVICE</p>
      </div>
      <div class="service-img2">
        <div class="service-img-cof">
          <%= image_tag("pen2.png", class:"service-list") %>
          <h1>作品のアップロード</h1>
            <div class="service-h2">
              <h2>ワンクリックで簡単に投稿できます。作品数に制限もありません。</h2>
            </div>
        </div>
        <div class="service-img-cof">
            <%= image_tag("plofile.png", class:"service-list") %>
            <h1>プロフィールの作成</h1>
          <div class="service-h2">
            <h2>プロフィールの公開や編集が行えます。SNSへの誘導も可能です。</h2>
          </div>
        </div>
        <div class="service-img-cof">
          <%= image_tag("dustbox.png", class:"service-list") %>
          <h1>作品の削除</h1>
          <div class="service-h2">
            <h2>作品の削除が簡単に行えます。</h2>
          </div>
        </div>
        <div class="service-img-cof">
            <%= image_tag("config.png", class:"service-list") %>
            <h1>作品の修正や編集</h1>
          <div class="service-h2">
            <h2>作品の修正や編集がワンクリックで行えます。</h2>
          </div>
        </div>
    </div>
  </div>
  <div class="service-que">
    <div class="service-que-box"></div>
      <div class="service-que2">
        <%= image_tag("border2.png", class:"border3") %>
        <%= image_tag("servicedes.png", class:"service-logo") %>
        <%= image_tag("try.png", class:"try") %>
        <%= image_tag("try3.png", class:"try3") %>
      </div>
      <div class="service-contents">
        <div class="service-custom">
        <p>お気軽にご質問・ご相談ください</p>
        </div>
        <div class="service-border0">
          <div class="service-border1"></div>
          <div class="service-border2"></div>
        </div>

        <div class="service-content-box">
          <div class="service-content">
            <%= image_tag("PDF.png", class:"service-content-pdf") %>
            <p>資料をダウンロード</p>
          </div>
          <div class="service-content">
            <%= image_tag("call.png") %>
            <p>リモートでお問い合わせ</p>
          </div>
          <div class="service-content">
            <%= image_tag("mail.png", class:"service-content-mail") %>
            <p>メールでお問い合わせ</p>
          </div>
        </div>
      </div>
  </div>


  <footer>
    <%= image_tag("logo-white.png", class:"footer-logo") %>
    <ul class="footer-list">
      <li>home</li>
      <li><%= link_to 'sample', user_path(44), class: "footer-sample" %></li>
      <li>service</li>
    </ul>
    <p class="footer-font">2021 portplus</p>
  </footer>

app/views/works/indextop.html.erb
<div class="slide3">
  <header>
    <%= image_tag("portplus-logo2.png", class:"portplus-logo2") %>
    <%= link_to 'sample', user_path(44), class: "sumple" %>
  </header>
  <div class="background2">
      <P> make up portfolio </p>
      <h1 class="port-text">あなたの作品に色付けを。</h1>
      <h2 class="port-text-sub">オリジナルのポートフォリオを作成しましょう。</h2>
      <h2> <span class="font_color">picture</span> / <span class="font_color2">illustration</span> / <span class="font_color3">design</span>  ... </h2>
    <div class="session">
          <% if user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
            <li><%= link_to 'マイページへ', user_path(current_user.id), class: "logout" %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
          <% end %>
    </div>
  </div>
</div>

app/views/works/new.html.erb
<div class="sign-up-logo1">
<%= image_tag "portplus.flower.png", class:"flower" %>
<%= link_to image_tag("portplus-logo2.png", class:"sign-up-logo2"), user_path(current_user.id) %>
</div>
<div class="sign-up-message">
<p class="new-work-font">NEW WORK !!</p>
</div>

<%= form_with model: @work, class: 'registration-main', local: true do |f| %>
<div class="sign-up-page">

<div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">タイトル</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :title, class:"input-genre", id:"title", placeholder:"任意" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">キャッチコピー(任意)</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :catch_copy, class:"input-genre", id:"catch_copy", placeholder:"任意" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">コンセプト(任意)</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :concept, class:"input-genre", id:"concept", placeholder:"任意" %>
    </div>
  </div>

      <div class="form-group">
      <div class="click-upload">
        <P>作品を選択 ※必須</p>
        <%= f.file_field :image, id:"header-image" %>
      </div>
    </div>

  <div class="sign-up-btn">
      <%= f.submit "登録", class:"sign-up-color-btn" %>
  </div>
</div>
<% end %>

app/views/works/show.html.erb
<div id="hamburger">
  <span class="inner_line" id="line1"></span>
  <span class="inner_line" id="line2"></span>
  <span class="inner_line" id="line3"></span>
</div>


<nav id="nav">
  <ul>
    <% if user_signed_in? %>
    <% if current_user.id == @work.user_id %>
    <li><%= link_to "EDIT WORK", edit_work_path, class:"toplink"%></li>
    <% end %>
    <% end %>
    <li><%= link_to "TOP PAGE", indextop_works_path, class:"toplink"%></li>
    <% if user_signed_in? %>
    <% if current_user.id == @work.user_id %>
    <li><%= link_to "DELETE WORK", work_path, method: :delete, class:"toplink" %></li>
    <% end %>
    <% end %>
  </ul>
</nav>
<% if @work.title.blank? %>
<div class="work-title-nil">
<span>&thinsp;-WORK-</span>
</div>
<% else %>
<div class="work-title2">
<span>&thinsp;-WORK-</span>
  <div class="work-name">
    <%= @work.title %>
  </div>
</div>
<% end %>

<div class="show-image">
  <%= image_tag @work.image, class: :image_size %>
</div>

<% unless @work.catch_copy.blank? %>
<div class="work-title3">
<span>&thinsp;-catch copy-</span>
  <div class="work-temple">
    <%= @work.catch_copy %>
  </div>
</div>
<% end %>

<% unless @work.concept.blank? %>
<div class="work-title4">
<span>&thinsp;-concept-</span>
<div class="work-temple">
<%= @work.concept %>
</div>
</div>
<% end %>



<div class="site-header-show">
<p class="site-header">2021 portplus+ All Rights Reserved.</p>
</div>